### ISSUE TITLE
Font cache checks for wrong name

### ISSUE THREAD

**Issue by andras-gerendas** [lisawray/fontbinding#5]
In the font cache the font is stored in the cache with the filename, but when this font is needed for another time the containsKey checks for the alias of the font.

Example:
fontFilename: MyFont-SemiBold.otf
stored in cache: fontFilename
checked: filename (myfont-semibold) [which is the alias]

**Comment by lisawray** [comment]
All better: https://github.com/lisawray/fontbinding/pull/4
