### ISSUE TITLE
Should it work to use this method with Design Support components and custom layouts?

### ISSUE THREAD

**Issue by nilsi** [lisawray/fontbinding#8]
In my project I have both a TabLayout and a NavigationDrawer.

For the `TabLayout` I inflate each tab as a custom layout. Like this:

```
LinearLayout appTab = (LinearLayout) LayoutInflater.from(activity).inflate(R.layout.custom_tab, null);
TextView appCardsTextView = (TextView) appTab.findViewById(R.id.tab_text);
appCardsTextView.setText("Application");
ImageView appCardsImageView = (ImageView) appTab.findViewById(R.id.tab_icon);
appCardsImageView.setImageResource(R.drawable.ic_application);
tabLayout.getTabAt(0).setCustomView(appTab);
```

 custom_tab.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<layout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>
    </data>

    <LinearLayout
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:gravity="center_vertical|center_horizontal">

        <ImageView
            android:layout_width="34dp"
            android:layout_height="34dp"
            android:id="@+id/tab_icon"/>

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:id="@+id/tab_text"
            android:textColor="@color/white"
            android:textSize="@dimen/tab_label"
            android:text="testing"
            app:font="@{`lato_hairline`}" <---- NOT WORKING!
        />

    </LinearLayout>

</layout>
```

Is there a way to make it set the font in a situation like this through XML? 
I found a workaround setting it through Java that I use for now:
`appCardsTextView.setTypeface(FontCache.getInstance(appCardsTextView.getContext()).get("lato_hairline"));`
But for XML it does not bind to the `BindingAdapter`

I have the same problem for my `NavigationView` (sidebar) where I might have to get each item and set it through Java as well.

Thanks.

**Comment by lisawray** [comment]
For the TabLayout, you need to inflate the layout using data binding.  Try this:

```
ViewDataBinding binding = DataBindingUtil.inflate(LayoutInflater.from(activity), R.layout.custom_tab, null, false);
LinearLayout appTab = (LinearLayout) binding.getRoot();
```

Then, proceed from there as usual.

The `NavigationView` is a good question.  I don't think it's possible to use this method if you don't have control over the inflation of the child views, or have access to bind them afterward.  In this case, I'd recommend that you use a `ListView` or `RecyclerView` inside the `NavigationView` and populate it yourself with a custom layout including a TextView with a custom font.

**Comment by nilsi** [comment]
Thanks, I will try next week! Indeed I don't think it's possible for NavigationView but hope it will work for the TabLayout. I ended up doing this for the NavigationView last week:

http://stackoverflow.com/questions/39324572/android-support-library-get-title-textview-from-navigationview

Will close this one since I don't think we are getting any further for now.

**Comment by lisawray** [comment]
@nilsi spans are another great idea!  I use a similar method for the titles of `Toolbar`s.  I think that's the best you're likely to get if you want to rely on `NavigationView` as having a `Menu`.
